# Stage 1: Builder
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Устанавливаем swag для генерации документации
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Копируем зависимости и скачиваем
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь проект
COPY . .

# Генерируем Swagger
RUN swag init -g cmd/main.go

# Сборка бинарника
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/server ./cmd/

# Stage 2: Final image
FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /app

# Копируем бинарник
COPY --from=builder /app/bin/server .

# Порт приложения
EXPOSE 8081

# Запуск
ENTRYPOINT ["./server"]
