FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN swag init -g cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/server ./cmd/

FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /app
COPY --from=builder /app/bin/server .

EXPOSE 8080

ENTRYPOINT ["./server"]